In [15]:
# Dependencies and Setup
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# File to Load (Remember to Change These)
russia_data = "../russian_demography_2.csv"

# Read the Mouse and Drug Data and the Clinical Trial Data
russia_df = pd.read_csv(russia_data)
russia_df

,year,region,npg,birth_rate,death_rate,migratory_growth,population
0,1990,Republic of Adygea,1.9,14.2,12.3,NaN,434788.0
1,1990,Altai Krai,1.8,12.9,11.1,NaN,2640419.0
2,1990,Amur Oblast,7.6,16.2,8.6,NaN,1055337.0
3,1990,Arkhangelsk Oblast,3.7,13.5,9.8,NaN,1523509.0
4,1990,Astrakhan Oblast,4.7,15.1,10.4,NaN,997516.0
...,...,...,...,...,...,...,...
2375,2017,Chuvash Republic,-1.3,11.3,12.6,-2.519,NaN
2376,2017,Chukotka Autonomous Okrug,3.7,13.1,9.4,-13.230,NaN
2377,2017,Sakha (Yakutia) Republic,6.4,14.5,8.1,-4.825,NaN
2378,2017,Yamalo-Nenets Autonomous Okrug,9.1,14.0,4.9,-4.500,NaN
2379,2017,Yaroslavl Oblast,-4.7,10.5,15.2,0.714,NaN